version: '3'

services:
  inpit-sqlite:
    image: inpit-sqlite:latest
    container_name: inpit-sqlite
    build:
      context: ../container/inpit-sqlite
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./data-inpit-sqlite:/app/data:z
    user: "ec2-user:ec2-user"  # Run as ec2-user to match file ownership
    restart: unless-stopped

  inpit-sqlite-mcp:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: inpit-sqlite-mcp
    environment:
      - INPIT_API_URL=http://inpit-sqlite:5001
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-northeast-1
      - GCP_CREDENTIALS_S3_BUCKET=ndi-3supervision
      - GCP_CREDENTIALS_S3_KEY=MIT/GCPServiceKey/tosapi-bf0ac4918370.json
    ports:
      - "8000:8000"
    volumes:
      - ./data-inpit-sqlite-mcp:/app/data:z
    user: "ec2-user:ec2-user"  # Run as ec2-user
    depends_on:
      - inpit-sqlite
    restart: unless-stopped
