---
apiVersion: v1
kind: Service
metadata:
  name: orgmgmt-frontend
  namespace: default
  labels:
    app: orgmgmt-frontend
spec:
  type: LoadBalancer
  externalIPs:
  - 10.0.1.84
  ports:
  - name: http
    port: 5006
    targetPort: 80
    protocol: TCP
  selector:
    app: orgmgmt-frontend
