version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: git-playground
    ports:
      - "3000:3000"
    volumes:
      - .:/app:z,U
      - /app/node_modules
    user: "root:root"
    # Volume mounts with z flag for SELinux and setting host user permissions
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_HOST_URL=mcp.shift-terminus.com
    # Use the HEALTHCHECK from Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s