version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: git-playground
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_HOST_URL=mcp.shift-terminus.com
    command: sh -c "npm install && npm run dev"