version: '3.8'

services:
  orgmgmt-backend:
    image: localhost:5005/orgmgmt/backend:v1.0.0
    container_name: orgmgmt-backend-prod
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=orgmgmt
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL:-WARN}
    networks:
      - argocd-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 60s
    depends_on:
      - postgres

  orgmgmt-frontend:
    image: localhost:5005/orgmgmt/frontend:v1.0.0
    container_name: orgmgmt-frontend-prod
    ports:
      - "5008:80"
    environment:
      - API_URL=http://orgmgmt-backend-prod:8080
    networks:
      - argocd-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
    depends_on:
      - orgmgmt-backend

networks:
  argocd-network:
    external: true
