AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation Template to launch an EC2 instance with Docker and Python 3.12 in a container, with pip libraries installed.
  Ports 7474 and 7687 and 7575 and 7587 are open for external access. Resources are suffixed with SHIFT-graphRAG.

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select an existing EC2 KeyPair for SSH access (optional)
    Default: ""

  AccessKeyIdParam:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Access Key ID from Parameter Store
    Default: "/adminOpe/accessKey/aws_access_key_id" # Parameter Store のパラメータ名

  SecretAccessKeyParam:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Secret Access Key from Parameter Store
    Default: "/adminOpe/accessKey/aws_secret_access_key" # Parameter Store のパラメータ名

  RegionNameParam:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Secret Access Key from Parameter Store
    Default: "/adminOpe/accessKey/aws_region_name" # Parameter Store のパラメータ名

  GithubPrivateKey:
    Type: AWS::SSM::Parameter::Value<String> # 👈  AWS::SSM::Parameter::Value<String> を指定
    Description: GitHub private key from Parameter Store
    Default: "/adminOpe/github/privateKey" # 👈 Parameter Store のパラメータ名 (SecureString)

  GithubPublicKey:
    Type: AWS::SSM::Parameter::Value<String> # 👈  AWS::SSM::Parameter::Value<String> を指定
    Description: GitHub public key from Parameter Store
    Default: "/adminOpe/github/publicKey" # 👈 Parameter Store のパラメータ名 (SecureString)

  InstanceType:
    Type: String
    Description: Select the instance type (t3 series only)
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge

Conditions:
  UseKeyPairParameter: !Not [!Equals [!Ref KeyName, ""]]

Resources:
  # VPC
  VPCSHIFTgraphRAG:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-SHIFT-graphRAG

  # Internet Gateway
  InternetGatewaySHIFTgraphRAG:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGW-SHIFT-graphRAG

  AttachGatewaySHIFTgraphRAG:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCSHIFTgraphRAG
      InternetGatewayId: !Ref InternetGatewaySHIFTgraphRAG

  # Public Subnet
  PublicSubnetSHIFTgraphRAG:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCSHIFTgraphRAG
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: PublicSubnet-SHIFT-graphRAG

  # Private Subnet
  PrivateSubnetSHIFTgraphRAG:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCSHIFTgraphRAG
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: PrivateSubnet-SHIFT-graphRAG

  # Route Table for Public Subnet
  PublicRouteTableSHIFTgraphRAG:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCSHIFTgraphRAG
      Tags:
        - Key: Name
          Value: PublicRT-SHIFT-graphRAG

  PublicRouteSHIFTgraphRAG:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTableSHIFTgraphRAG
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGatewaySHIFTgraphRAG

  PublicSubnetRouteTableAssociationSHIFTgraphRAG:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetSHIFTgraphRAG
      RouteTableId: !Ref PublicRouteTableSHIFTgraphRAG

  # Security Group
  EC2SecurityGroupSHIFTgraphRAG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: EC2SG-SHIFT-graphRAG
      GroupDescription: Allow SSH, Neo4j ports (7474, 7687, 7575, 7587)
      VpcId: !Ref VPCSHIFTgraphRAG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 7474
          ToPort: 7474
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 7687
          ToPort: 7687
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 7575
          ToPort: 7575
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 7587
          ToPort: 7587
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EC2SG-SHIFT-graphRAG

  # IAM Role for EC2
  EC2InstanceRoleSHIFTgraphRAG:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies: # インラインポリシーを追加
        - PolicyName: ParameterStoreAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: # Parameter Store パラメータの ARN を指定 (後で修正)
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/adminOpe/accessKey/aws_access_key_id"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/adminOpe/accessKey/aws_secret_access_key"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/adminOpe/accessKey/aws_region_name"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/adminOpe/github/privateKey"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/adminOpe/github/publicKey"

  EC2InstanceProfileSHIFTgraphRAG:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRoleSHIFTgraphRAG

  # EC2 Instance
  EC2InstanceSHIFTgraphRAG:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c7af5fe939f2677f  # Red Hat Enterprise Linux 8 (us-east-1)
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PublicSubnetSHIFTgraphRAG
      SecurityGroupIds:
        - !Ref EC2SecurityGroupSHIFTgraphRAG
      IamInstanceProfile: !Ref EC2InstanceProfileSHIFTgraphRAG
      KeyName: !If [UseKeyPairParameter, !Ref KeyName, !Ref "AWS::NoValue"]
      BlockDeviceMappings:
        - DeviceName: /dev/sda1  # ルートデバイス
          Ebs:
            VolumeSize: 100      # ✅ ディスクサイズ (GB)
            VolumeType: gp3      # ボリュームタイプ (推奨: gp3)
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: EC2Instance-SHIFT-graphRAG
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -x
          # 1. AWS CloudWatch AgentのRPMパッケージをダウンロード
          curl -O https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm

          # 2. RPMパッケージをインストール
          dnf install -y ./amazon-cloudwatch-agent.rpm

          # 3. ログ追加
          cat <<EOF > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/log/messages",
                      "log_group_name": "SHIFT-graphRAG-EC2-Messages",
                      "log_stream_name": "{instance_id}-messages"
                    },
                    {
                      "file_path": "/var/log/docker.log",
                      "log_group_name": "SHIFT-graphRAG-EC2-Docker",
                      "log_stream_name": "{instance_id}-docker"
                    }
                  ]
                }
              }
            }
          }
          EOF

          # 4. CloudWatch Agentの起動と自動起動の有効化
          systemctl enable amazon-cloudwatch-agent
          systemctl start amazon-cloudwatch-agent
          

          # Install Docker etc...
          dnf install -y docker awscli git bash-completion python3-pip
          systemctl start docker
          systemctl enable docker
          pip install podman-compose

          #あとでロールに切り替える予定
          mkdir -p /root/.aws
          echo "[default]" > /root/.aws/credentials
          echo "aws_access_key_id='${AccessKeyIdParam}'" >> /root/.aws/credentials
          echo "aws_secret_access_key='${SecretAccessKeyParam}'" >> /root/.aws/credentials
          chmod 600 /root/.aws/credentials
          echo "[default]" > /root/.aws/config
          echo "region='${RegionNameParam}'" >> /root/.aws/config
          chmod 600 /root/.aws/config

          curl -L https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker \
          -o /etc/bash_completion.d/docker
          echo ". /usr/share/bash-completion/bash_completion" >> /root/.bashrc
          echo ". /etc/bash_completion.d/docker" >> /root/.bashrc

          echo "export AWS_ACCESS_KEY_ID='${AccessKeyIdParam}'" >> /root/.bashrc
          echo "export AWS_SECRET_ACCESS_KEY='${SecretAccessKeyParam}'" >> /root/.bashrc
          echo "export AWS_DEFAULT_REGION='${RegionNameParam}'" >> /root/.bashrc

          mkdir -p /root/.ssh
          echo "${GithubPrivateKey}" > /root/.ssh/id_ed25519
          chmod 400 /root/.ssh/id_ed25519

          cat <<EOF > /root/.ssh/config
          Host github.com
            IdentityFile ~/.ssh/id_ed25519
            User git
          Host github.com
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
          EOF

          git clone git@github.com:shiftrepo/aws.git /root/aws.git
          git clone https://github.com/langfuse/langfuse.git -b v2.95.8 /root/langfuse_v2.git
          git clone https://github.com/langfuse/langfuse.git /root/langfuse_latest.git

          podman-compose --file /root/aws.git/container/docker-compose.yml up --build -d

          # コンテナ内の .bashrc に環境変数を設定
          docker exec python-aws bash -c "echo 'export AWS_ACCESS_KEY_ID=${AccessKeyIdParam}' >> ~/.bashrc"
          docker exec python-aws bash -c "echo 'export AWS_SECRET_ACCESS_KEY=${SecretAccessKeyParam}' >> ~/.bashrc"
          docker exec python-aws bash -c "echo 'export AWS_DEFAULT_REGION=${RegionNameParam}' >> ~/.bashrc"
          docker cp ~/aws.git/app/. python-aws:/root/app

Outputs:
  VPCId:
    Description: Created VPC ID
    Value: !Ref VPCSHIFTgraphRAG
  PublicSubnetId:
    Description: Created Public Subnet ID
    Value: !Ref PublicSubnetSHIFTgraphRAG
  PrivateSubnetId:
    Description: Created Private Subnet ID
    Value: !Ref PrivateSubnetSHIFTgraphRAG
  EC2InstanceId:
    Description: Launched EC2 Instance ID
    Value: !Ref EC2InstanceSHIFTgraphRAG
  PublicIP:
    Description: Public IP of the EC2 Instance
    Value: !GetAtt EC2InstanceSHIFTgraphRAG.PublicIp