version: '3'

services:
  patentdwh-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: patentdwh-db
    ports:
      - "5002:5002"
    volumes:
      - ./data:/app/data:z
    environment:
      - PORT=5002
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # Note: AWS_REGIONは使わず、AWS_DEFAULT_REGIONを利用すること。
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-northeast-1}
      - SKIP_DATA_DOWNLOAD=false
    user: "root:root"
    restart: unless-stopped
    networks:
      - patent-network

  patentdwh-mcp-enhanced:
    build:
      context: ./app
      dockerfile: Dockerfile.enhanced
    container_name: patentdwh-mcp-enhanced
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PATENT_DB_URL=http://patentdwh-db:5002
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # Note: AWS_REGIONは使わず、AWS_DEFAULT_REGIONを利用すること。
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - GCP_CREDENTIALS_S3_BUCKET=ndi-3supervision
      - GCP_CREDENTIALS_S3_KEY=MIT/GCPServiceKey/tosapi-bf0ac4918370.json
    volumes:
      - ./data:/app/data:z
      - ./data/db:/app/data/db:z
    user: "root:root"
    depends_on:
      - patentdwh-db
    restart: unless-stopped
    networks:
      - patent-network

networks:
  patent-network:
    driver: bridge
