version: '3'

# Force recreate all containers
x-force-recreate: &force-recreate
  restart: "no"
  stop_grace_period: "0s"

services:
  # PatentDWH DB Service - Core database service
  patentdwh-db:
    <<: *force-recreate
    build:
      context: ./db
    container_name: patentdwh-db
    volumes:
      - ./data:/app/data:z
    environment:
      - PORT=5002
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # Note: AWS_REGIONは使わず、AWS_DEFAULT_REGIONを利用すること。
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-northeast-1}
      - SKIP_DATA_DOWNLOAD=false
    user: "root:root"  # Run as root
    networks:
      - patent-network

  # PatentDWH MCP Enhanced Service - MCP server with LangChain integration
  patentdwh-mcp-enhanced:
    <<: *force-recreate
    build:
      context: ./app
      dockerfile: Dockerfile.enhanced
    container_name: patentdwh-mcp-enhanced
    environment:
      - PORT=8080
      - PATENT_DB_URL=http://patentdwh-db:5002
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # Note: AWS_REGIONは使わず、AWS_DEFAULT_REGIONを利用すること。
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - GCP_CREDENTIALS_S3_BUCKET=ndi-3supervision
      - GCP_CREDENTIALS_S3_KEY=MIT/GCPServiceKey/tosapi-bf0ac4918370.json
    volumes:
      - ./data:/app/data:z
      - ./data/db:/app/data/db:z
    user: "root:root"  # Run as root
    depends_on:
      - patentdwh-db
    networks:
      - patent-network

  # Patent Analysis Service - For analyzing patent data
  patent-analysis:
    <<: *force-recreate
    build:
      context: ../patent_analysis_container
    container_name: patent-analysis
    volumes:
      - ../patent_analysis_container/output:/app/output:z
    environment:
      - MCP_URL=http://patentdwh-mcp-enhanced:8080/api/v1/mcp
      - DB_URL=http://patentdwh-db:5002/api/sql-query
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # Note: AWS_REGIONは使わず、AWS_DEFAULT_REGIONを利用すること。
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    user: "root:root"  # Run as root to fix permission issues
    networks:
      - patent-network
    depends_on:
      - patentdwh-mcp-enhanced
    # Command will be provided when running the container

networks:
  patent-network:
    driver: bridge
