version: '3'

services:
  patentdwh-db:
    container_name: patentdwh-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-northeast-1
      - SKIP_DATA_DOWNLOAD=false
    volumes:
      - ./data:/app/data:z
    user: "root:root"  # Run as root
    restart: unless-stopped

  patentdwh-mcp:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: patentdwh-mcp
    environment:
      - PATENT_DB_URL=http://patentdwh-db:5002
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-northeast-1
      - GCP_CREDENTIALS_S3_BUCKET=ndi-3supervision
      - GCP_CREDENTIALS_S3_KEY=MIT/GCPServiceKey/tosapi-bf0ac4918370.json
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data:z
      - ./data/db:/app/data/db:z
    user: "root:root"  # Run as root
    depends_on:
      - patentdwh-db
    restart: unless-stopped
