---
apiVersion: v1
kind: Service
metadata:
  name: orgmgmt-frontend
  namespace: default
  labels:
    app: orgmgmt-frontend
spec:
  type: NodePort
  sessionAffinity: None
  selector:
    app: orgmgmt-frontend
  ports:
    - name: http
      protocol: TCP
      port: 5006
      targetPort: 80
      nodePort: 30006
