version: '3.8'

services:
  claudecode:
    image: claudecode-node-slim:latest
    container_name: claude-code-node
    build:
      context: .
      dockerfile: node-slim.Dockerfile
    volumes:
      - ./workdir:/app/workdir:z
    environment:
      - GITLAB_HOST=gitlab
      - GITLAB_API_TOKEN=${GITLAB_API_TOKEN:-}
      - GITLAB_PERSONAL_ACCESS_TOKEN=${GITLAB_PERSONAL_ACCESS_TOKEN:-}
      - MCP_FILESYSTEM_ENABLED=1
      - MCP_SEQUENTIAL_THINKING_ENABLED=1
      - MCP_SQLITE_ENABLED=1
      - MCP_GIT_ENABLED=1
      - TZ=Asia/Tokyo
      - CLAUDE_CODE_USE_BEDROCK=${CLAUDE_CODE_USE_BEDROCK:-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL:-}
      - ANTHROPIC_SMALL_FAST_MODEL=${ANTHROPIC_SMALL_FAST_MODEL:-}
    networks:
      - gitlab-network
    depends_on:
      - gitlab
    command: ["/bin/bash"]
    stdin_open: true
    tty: true

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-node
    restart: always
    hostname: gitlab
    ports:
      - "8080:80"
      - "8443:443"
      - "2223:22"
    volumes:
      - gitlab-config:/etc/gitlab:z
      - gitlab-logs:/var/log/gitlab:z
      - gitlab-data:/var/opt/gitlab:z
    shm_size: 256m
    networks:
      - gitlab-network
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        gitlab_rails['initial_root_password'] = 'password123!'
        gitlab_rails['rate_limit_requests_per_period'] = 300
        gitlab_rails['rate_limit_period'] = 60

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  gitlab-network:
    name: gitlab-network