apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orgmgmt-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: file:///gitops
    targetRevision: HEAD
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
