apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orgmgmt-dev
  namespace: argocd
spec:
  project: orgmgmt
  source:
    repoURL: file:///gitops
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences: []
