version: '3.8'

services:
  patent-mcp-server:
    image: python:3.9-slim
    container_name: patent-mcp-server
    ports:
      - "8000:8000"
    volumes:
      - ..:/app:Z
    working_dir: /app/patent-mcp-server/app
    command: >
      bash -c "pip install -r requirements.txt &&
              python server.py"
    restart: unless-stopped
