version: '3.8'

services:
  # PostgreSQL Database - Configured for external access from anywhere
  postgres:
    image: docker.io/library/postgres:${POSTGRES_VERSION:-16-alpine}
    container_name: orgmgmt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-orgmgmt}
      POSTGRES_USER: ${POSTGRES_USER:-orgmgmt_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SecurePassword123!}
      PGDATA: /var/lib/postgresql/data/pgdata
      # Allow external connections from anywhere - NO SECURITY
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      # Bind to all interfaces to allow external connections
      - "0.0.0.0:${POSTGRES_PORT:-5001}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - argocd-network
    command: >
      postgres
      -c listen_addresses='*'
      -c max_connections=200
      -c shared_buffers=256MB
      -c log_statement='all'
      -c log_connections=on
      -c log_disconnections=on
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-orgmgmt_user} -d ${POSTGRES_DB:-orgmgmt}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin 4
  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: orgmgmt-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@orgmgmt.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-AdminPassword123!}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT:-5002}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - argocd-network
    depends_on:
      postgres:
        condition: service_healthy

  # Nexus Repository Manager
  nexus:
    image: docker.io/sonatype/nexus3:${NEXUS_VERSION:-3.63.0}
    container_name: orgmgmt-nexus
    restart: unless-stopped
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=2048m"
    ports:
      - "${NEXUS_HTTP_PORT:-8000}:8081"
      - "${NEXUS_DOCKER_PORT:-8082}:8082"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - argocd-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/service/rest/v1/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # GitLab CE
  # Redis for ArgoCD
  argocd-redis:
    image: docker.io/library/redis:7-alpine
    container_name: argocd-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - argocd-redis-data:/data
    networks:
      - argocd-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ArgoCD Repository Server
  argocd-repo-server:
    image: quay.io/argoproj/argocd:${ARGOCD_VERSION:-v2.10.0}
    container_name: argocd-repo-server
    restart: unless-stopped
    command: argocd-repo-server
    environment:
      ARGOCD_RECONCILIATION_TIMEOUT: "180s"
      ARGOCD_REPO_SERVER_LOGFORMAT: "text"
      ARGOCD_REPO_SERVER_LOGLEVEL: "info"
    volumes:
      - argocd-repo-data:/app/config
      - /root/aws.git/container/claudecode/ArgoCD/gitops:/gitops:ro,Z
    networks:
      - argocd-network
    healthcheck:
      test: ["CMD-SHELL", "test -S /tmp/argocd-repo-server.sock || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ArgoCD Application Controller
  argocd-application-controller:
    image: quay.io/argoproj/argocd:${ARGOCD_VERSION:-v2.10.0}
    container_name: argocd-application-controller
    restart: unless-stopped
    command: argocd-application-controller --status-processors 20 --operation-processors 10
    environment:
      ARGOCD_CONTROLLER_REPLICAS: "1"
      ARGOCD_RECONCILIATION_TIMEOUT: "180s"
      REDIS_SERVER: "argocd-redis:6379"
    volumes:
      - argocd-controller-data:/app/config
      - /root/aws.git/container/claudecode/ArgoCD/gitops:/gitops:ro,Z
    networks:
      - argocd-network
    depends_on:
      argocd-redis:
        condition: service_healthy

  # ArgoCD API Server
  argocd-server:
    image: quay.io/argoproj/argocd:${ARGOCD_VERSION:-v2.10.0}
    container_name: argocd-server
    restart: unless-stopped
    command: argocd-server --insecure --staticassets /shared/app
    environment:
      ARGOCD_SERVER_INSECURE: "${ARGOCD_SERVER_INSECURE:-true}"
      ARGOCD_SERVER_ROOTPATH: "/"
      REDIS_SERVER: "argocd-redis:6379"
    ports:
      - "${ARGOCD_SERVER_PORT:-5010}:8080"
    volumes:
      - argocd-server-data:/app/config
      - /root/aws.git/container/claudecode/ArgoCD/gitops:/gitops:ro,Z
    networks:
      - argocd-network
    depends_on:
      argocd-redis:
        condition: service_healthy
      argocd-repo-server:
        condition: service_started
      argocd-application-controller:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  argocd-network:
    driver: bridge
    name: argocd-network

volumes:
  postgres-data:
    name: orgmgmt-postgres-data
  pgadmin-data:
    name: orgmgmt-pgadmin-data
  nexus-data:
    name: orgmgmt-nexus-data
  argocd-redis-data:
    name: argocd-redis-data
  argocd-repo-data:
    name: argocd-repo-data
  argocd-controller-data:
    name: argocd-controller-data
  argocd-server-data:
    name: argocd-server-data
