-- ユーザーテーブル
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    phone VARCHAR2(20),
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    is_active NUMBER(1) DEFAULT 1,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_is_active CHECK (is_active IN (0, 1))
);

-- カラムコメント
COMMENT ON COLUMN users.user_id IS 'ユーザーID（主キー）';
COMMENT ON COLUMN users.username IS 'ユーザー名（ログイン用）';
COMMENT ON COLUMN users.email IS 'メールアドレス';
COMMENT ON COLUMN users.password_hash IS 'パスワードハッシュ値';
COMMENT ON COLUMN users.first_name IS '名';
COMMENT ON COLUMN users.last_name IS '姓';
COMMENT ON COLUMN users.phone IS '電話番号';
COMMENT ON COLUMN users.created_at IS 'レコード作成日時';
COMMENT ON COLUMN users.updated_at IS 'レコード更新日時';
COMMENT ON COLUMN users.is_active IS 'アクティブフラグ（1:有効、0:無効）';

-- テーブルコメント
COMMENT ON TABLE users IS 'ユーザー情報を管理するテーブル';