-- カテゴリテーブル
CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2(100) NOT NULL,
    description CLOB,
    parent_category_id NUMBER,
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT pk_categories PRIMARY KEY (category_id),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_category_id) REFERENCES categories(category_id)
);

-- カラムコメント
COMMENT ON COLUMN categories.category_id IS 'カテゴリーID（主キー）';
COMMENT ON COLUMN categories.category_name IS 'カテゴリ名';
COMMENT ON COLUMN categories.description IS 'カテゴリ説明';
COMMENT ON COLUMN categories.parent_category_id IS '親カテゴリーID（階層構造用）';
COMMENT ON COLUMN categories.created_at IS 'レコード作成日時';

-- テーブルコメント
COMMENT ON TABLE categories IS '商品カテゴリ情報を管理するテーブル';