-- 商品テーブル
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR2(200) NOT NULL,
    description CLOB,
    price NUMBER(10, 2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0,
    category_id NUMBER,
    sku VARCHAR2(50),
    weight NUMBER(8, 2),
    dimensions VARCHAR2(100),
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    is_active NUMBER(1) DEFAULT 1,
    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT uk_products_sku UNIQUE (sku),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(category_id),
    CONSTRAINT ck_products_is_active CHECK (is_active IN (0, 1)),
    CONSTRAINT ck_products_price CHECK (price >= 0),
    CONSTRAINT ck_products_stock CHECK (stock_quantity >= 0)
);

-- カラムコメント
COMMENT ON COLUMN products.product_id IS '商品ID（主キー）';
COMMENT ON COLUMN products.product_name IS '商品名';
COMMENT ON COLUMN products.description IS '商品説明文';
COMMENT ON COLUMN products.price IS '商品価格（円）';
COMMENT ON COLUMN products.stock_quantity IS '在庫数量';
COMMENT ON COLUMN products.category_id IS 'カテゴリーID（外部キー）';
COMMENT ON COLUMN products.sku IS '商品管理コード（Stock Keeping Unit）';
COMMENT ON COLUMN products.weight IS '商品重量（kg）';
COMMENT ON COLUMN products.dimensions IS '商品サイズ情報';
COMMENT ON COLUMN products.created_at IS 'レコード作成日時';
COMMENT ON COLUMN products.updated_at IS 'レコード更新日時';
COMMENT ON COLUMN products.is_active IS '销売状態（1:销売中、0:销売停止）';

-- テーブルコメント
COMMENT ON TABLE products IS '商品情報を管理するテーブル';