-- 住所テーブル
CREATE TABLE addresses (
    address_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    address_type VARCHAR2(10) NOT NULL,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    company VARCHAR2(100),
    address_line1 VARCHAR2(255) NOT NULL,
    address_line2 VARCHAR2(255),
    city VARCHAR2(100) NOT NULL,
    state_province VARCHAR2(100),
    postal_code VARCHAR2(20) NOT NULL,
    country VARCHAR2(100) NOT NULL,
    created_at DATE DEFAULT SYSDATE,
    is_default NUMBER(1) DEFAULT 0,
    CONSTRAINT pk_addresses PRIMARY KEY (address_id),
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_addresses_type CHECK (address_type IN ('billing', 'shipping')),
    CONSTRAINT ck_addresses_is_default CHECK (is_default IN (0, 1))
);

-- カラムコメント
COMMENT ON COLUMN addresses.address_id IS '住所ID（主キー）';
COMMENT ON COLUMN addresses.user_id IS 'ユーザーID（外部キー）';
COMMENT ON COLUMN addresses.address_type IS '住所タイプ（billing:請求先、shipping:配送先）';
COMMENT ON COLUMN addresses.first_name IS '名（配送用）';
COMMENT ON COLUMN addresses.last_name IS '姓（配送用）';
COMMENT ON COLUMN addresses.company IS '会社名';
COMMENT ON COLUMN addresses.address_line1 IS '住敢1行目';
COMMENT ON COLUMN addresses.address_line2 IS '住敢2行目';
COMMENT ON COLUMN addresses.city IS '市区町村';
COMMENT ON COLUMN addresses.state_province IS '都道府県';
COMMENT ON COLUMN addresses.postal_code IS '郵便番号';
COMMENT ON COLUMN addresses.country IS '国名';
COMMENT ON COLUMN addresses.created_at IS 'レコード作成日時';
COMMENT ON COLUMN addresses.is_default IS 'デフォルト住所フラグ（1:デフォルト、0:非デフォルト）';

-- テーブルコメント
COMMENT ON TABLE addresses IS 'ユーザーの住所情報を管理するテーブル';