-- 注文テーブル
CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    order_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'pending',
    total_amount NUMBER(10, 2) NOT NULL,
    shipping_address_id NUMBER,
    billing_address_id NUMBER,
    payment_method VARCHAR2(50),
    shipping_cost NUMBER(10, 2) DEFAULT 0,
    tax_amount NUMBER(10, 2) DEFAULT 0,
    notes CLOB,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_orders_shipping_addr FOREIGN KEY (shipping_address_id) REFERENCES addresses(address_id),
    CONSTRAINT fk_orders_billing_addr FOREIGN KEY (billing_address_id) REFERENCES addresses(address_id),
    CONSTRAINT ck_orders_status CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
    CONSTRAINT ck_orders_total_amount CHECK (total_amount >= 0),
    CONSTRAINT ck_orders_shipping_cost CHECK (shipping_cost >= 0),
    CONSTRAINT ck_orders_tax_amount CHECK (tax_amount >= 0)
);

-- カラムコメント
COMMENT ON COLUMN orders.order_id IS '注文ID（主キー）';
COMMENT ON COLUMN orders.user_id IS '注文者ユーザーID（外部キー）';
COMMENT ON COLUMN orders.order_date IS '注文日時';
COMMENT ON COLUMN orders.status IS '注文状態（pending:保留中、processing:処理中、shipped:配送済み、delivered:配送完了、cancelled:キャンセル）';
COMMENT ON COLUMN orders.total_amount IS '注文合計金額（円）';
COMMENT ON COLUMN orders.shipping_address_id IS '配送先住所ID（外部キー）';
COMMENT ON COLUMN orders.billing_address_id IS '請求先住所ID（外部キー）';
COMMENT ON COLUMN orders.payment_method IS '支払方法';
COMMENT ON COLUMN orders.shipping_cost IS '配送料（円）';
COMMENT ON COLUMN orders.tax_amount IS '消費税額（円）';
COMMENT ON COLUMN orders.notes IS '注文備考';

-- テーブルコメント
COMMENT ON TABLE orders IS '注文情報を管理するテーブル';