-- 注文詳細テーブル
CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER,
    product_id NUMBER,
    quantity NUMBER NOT NULL,
    unit_price NUMBER(10, 2) NOT NULL,
    total_price NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (order_item_id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_items_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_total_price CHECK (total_price >= 0)
);

-- カラムコメント
COMMENT ON COLUMN order_items.order_item_id IS '注文明細ID（主キー）';
COMMENT ON COLUMN order_items.order_id IS '注文ID（外部キー）';
COMMENT ON COLUMN order_items.product_id IS '商品ID（外部キー）';
COMMENT ON COLUMN order_items.quantity IS '注文数量';
COMMENT ON COLUMN order_items.unit_price IS '単価（注文時点の価格）';
COMMENT ON COLUMN order_items.total_price IS '合計金額（単価 × 数量）';

-- テーブルコメント
COMMENT ON TABLE order_items IS '注文明細情報を管理するテーブル';