-- ショッピングカートテーブル
CREATE TABLE cart_items (
    cart_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    product_id NUMBER,
    quantity NUMBER NOT NULL,
    added_at DATE DEFAULT SYSDATE,
    CONSTRAINT pk_cart_items PRIMARY KEY (cart_item_id),
    CONSTRAINT uk_cart_items_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_cart_items_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE,
    CONSTRAINT ck_cart_items_quantity CHECK (quantity > 0)
);

-- カラムコメント
COMMENT ON COLUMN cart_items.cart_item_id IS 'カートアイテムID（主キー）';
COMMENT ON COLUMN cart_items.user_id IS 'ユーザーID（外部キー）';
COMMENT ON COLUMN cart_items.product_id IS '商品ID（外部キー）';
COMMENT ON COLUMN cart_items.quantity IS 'カート内数量';
COMMENT ON COLUMN cart_items.added_at IS 'カート追加日時';

-- テーブルコメント
COMMENT ON TABLE cart_items IS 'ショッピングカート情報を管理するテーブル';