-- レビューテーブル
CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id NUMBER,
    user_id NUMBER,
    rating NUMBER,
    title VARCHAR2(200),
    comment CLOB,
    created_at DATE DEFAULT SYSDATE,
    is_verified NUMBER(1) DEFAULT 0,
    CONSTRAINT pk_reviews PRIMARY KEY (review_id),
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_reviews_rating CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT ck_reviews_is_verified CHECK (is_verified IN (0, 1))
);

-- カラムコメント
COMMENT ON COLUMN reviews.review_id IS 'レビューID（主キー）';
COMMENT ON COLUMN reviews.product_id IS 'レビュー対象商品ID（外部キー）';
COMMENT ON COLUMN reviews.user_id IS 'レビュー投稿者ユーザーID（外部キー）';
COMMENT ON COLUMN reviews.rating IS '評価点数（1~5）';
COMMENT ON COLUMN reviews.title IS 'レビュータイトル';
COMMENT ON COLUMN reviews.comment IS 'レビューコメント内容';
COMMENT ON COLUMN reviews.created_at IS 'レビュー投稿日時';
COMMENT ON COLUMN reviews.is_verified IS 'レビュー承認フラグ（1:承認済み、0:未承認）';

-- テーブルコメント
COMMENT ON TABLE reviews IS '商品レビュー情報を管理するテーブル';